name: CI - Build and Push

on:
  push:
    branches: [ main ]
    tags: 
      - 'v*'
      - 'RC*'
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        default: 'dev'
        type: choice
        options: [dev, uat, prod]

env:
  AWS_REGION: us-east-1
  INFRA_REPO: ${{ github.repository }}-infra
  AWS_ACCOUNT_ID: "563571752566"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.TAG }}
      env: ${{ steps.vars.outputs.TARGET_ENV }}
    steps:
      - name: Determine Version and Environment
        id: vars
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            ENV="prod"
          elif [[ $GITHUB_REF == refs/tags/RC* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            ENV="uat"
          elif [ "${{ github.event_name }}" == "schedule" ]; then
            TAG="nightly-$(date +'%Y%m%d')"
            ENV="dev"
          else
            TAG="sha-${GITHUB_SHA::7}"
            ENV="dev"
          fi

          # Override env if manual trigger
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            ENV="${{ github.event.inputs.environment }}"
          fi

          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "TARGET_ENV=$ENV" >> $GITHUB_OUTPUT
          echo "Promoting $TAG to $ENV"

  build-and-push:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, vote, result, worker]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: voting-app-${{ matrix.service }}
          IMAGE_TAG: ${{ needs.setup.outputs.tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./${{ matrix.service }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          # Also tag as latest if it's a prod release
          if [ "${{ needs.setup.outputs.env }}" == "prod" ]; then
            docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          fi

  gitops-update:
    needs: [setup, build-and-push]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/voting-infra
          token: ${{ secrets.GITOPS_TOKEN }}
          path: infra

      - name: Update Kustomize
        env:
          ENV: ${{ needs.setup.outputs.env }}
          TAG: ${{ needs.setup.outputs.tag }}
          ECR_REGISTRY: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        run: |
          cd infra/k8s-specifications/overlays/$ENV
          
          # Update images
          kustomize edit set image frontend=$ECR_REGISTRY/voting-app-frontend:$TAG
          kustomize edit set image vote=$ECR_REGISTRY/voting-app-vote:$TAG
          kustomize edit set image result=$ECR_REGISTRY/voting-app-result:$TAG
          kustomize edit set image worker=$ECR_REGISTRY/voting-app-worker:$TAG

      - name: Commit and Push
        run: |
          cd infra
          git config user.name "GitHub Actions CI"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore(gitops): update ${{ needs.setup.outputs.env }} to ${{ needs.setup.outputs.tag }}"
          git push
